### ISSUE TITLE
Remove fullstop at end of summary

### ISSUE THREAD

**Issue by razzeee** [flathub/net.retrodeck.retrodeck#154]

**Comment by XargonWan** [comment]
Sorry can you please explain further?

**Comment by XargonWan** [comment]
Ok, this will be added in the 0.8.0b release (probably the next one).

https://github.com/XargonWan/RetroDECK/commit/563613d6719f47f2d001130bb3f623a48dac14a2

**Comment by XargonWan** [comment]
Added in 0.7.4b
