### ISSUE TITLE
`org.freedesktop.portal.*` permission is not necessary

### ISSUE THREAD

**Issue by bbhtt** [flathub/net.retrodeck.retrodeck#164]
This will be blocked in the linter soon. This issue is a heads-up for that.

See https://github.com/flathub-infra/flatpak-builder-lint/issues/178

**Comment by XargonWan** [comment]
Is there any way where I can notify the users of updates without `--talk-name=org.freedesktop.portal.Flatpak.UpdateMonitor`?

**Comment by bbhtt** [comment]
That works ootb, no need for any talk-name. Please see the issue I linked to.

**Comment by XargonWan** [comment]
Done in https://github.com/flathub/net.retrodeck.retrodeck/commit/76dc140aab8298ed6dfddd7bc19a286c8d4f95da, I would like to keep this issue opened until we are safe that everything works as expected, thanks.
