### ISSUE TITLE
RetroDECK is 0.4.0b instead of 0.4.3b on flathub

### ISSUE THREAD

**Issue by XargonWan** [flathub/net.retrodeck.retrodeck#4]
I noticed that the flathub build for some reason is older. 

I checked both of the repos and both are updated to 0.4.3b, what happened @barthalion ?

**Comment by barthalion** [comment]
```
~/.l/s/f/a/n/x/t/0/f/share ❱ grep 'release ve' appdata/net.retrodeck.retrodeck.appdata.xml
    <release version="0.4.2b" date="2022-05-11">
  <release version="0.4.1b" date="2022-05-11">
  <release version="0.4.0b" date="2022-05-26">
    <release version="0.3.1b" date="2022-04-26">
	<release version="0.3.0b" date="2022-04-26">
	<release version="0.2.0b" date="2022-04-17">
	<release version="0.1.1b" date="2022-04-03">
	<release version="0.1.0b" date="2022-04-03">
```

The value of both `version` and `date` field matter, not the order of `<release>` tags. And then, no commit since 02a0262eeee6d738dd859ff9cb9f8a767eb24e6a actually passed CI, which is why I mentioned before that maybe you shouldn't be merging changes which clearly don't build.
